apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2018-11-13T16:18:08Z
    labels:
      run: playload
    name: klaster-balancer-service
    namespace: default
    resourceVersion: "3069"
    selfLink: /api/v1/namespaces/default/services/klaster-balancer-service
    uid: b5518f6a-e75f-11e8-b58b-42010a800105
  spec:
    clusterIP: 10.31.245.226
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 32290
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      run: playload
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 35.232.208.234
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2018-11-13T15:48:42Z
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "6"
    selfLink: /api/v1/namespaces/default/services/kubernetes
    uid: 99001c8e-e75b-11e8-b58b-42010a800105
  spec:
    clusterIP: 10.31.240.1
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    sessionAffinity: ClientIP
    sessionAffinityConfig:
      clientIP:
        timeoutSeconds: 10800
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
